### PR TITLE
praat script and Jsonfiles

### PR DESCRIPTION
**Pull request by HoffmannAJ**

### CODE REVIEW

**Comment by psibre** [comment]
Unfortunately, you seem to be back where you were before we fixed your local master yesterday. You need to re-sync your local master with upstream:
```
git reset --hard upstream/master
```
Then cherry-pick only the commit with the Praat script:
```
git cherry-pick 25a96e0
```
Finally, replace your fork's master, which I believe will also strip the obsolete commits from this pull request:
```
git push origin master --force
```

**Comment by psibre** [comment]
The JSON file I would not (yet) commit, because

1. it doesn't quite conform to JSON syntax (all strings should be quoted), and
2. it can be generated from the TextGrid (the primary metadata) automatically, using, e.g., a gradle task.

We can think about including it later if it turns out that the alternative complicates the build too much.

**Comment by HoffmannAJ** [comment]
Thank you for your help!

I still get error messages when executing those commands.

------------------------------------------------------------------------------------

ANNE-JULIA@ANNE-JULIA-PC /d/Ella (master)
$ git reset -- hard upstram/master

ANNE-JULIA@ANNE-JULIA-PC /d/Ella (master)
$ git cherry-pick 25a96e0
On branch master
Your branch is up-to-date with 'origin/master'.

You are currently cherry-picking commit 25a96e0.

nothing to commit, working directory clean
The previous cherry-pick is now empty, possibly due to conflict resolution.
If you wish to commit it anyway, use:

    git commit --allow-empty

Otherwise, please use 'git reset'

ANNE-JULIA@ANNE-JULIA-PC /d/Ella (master|CHERRY-PICKING)
$ git push origin master -- force
error: src refspec force does not match any.
error: failed to push some refs to 'https://github.com/HoffmannAJ/EllaVator.git'

**Comment by psibre** [comment]
@HoffmannAJ after 7016369a97bf37974eb0fbcf318c8d8708786765 and 9b762ec642ba80adc1ea36190dcea6866f4b75fe, I would like to close this PR if you don't mind.

**Pull request closed without merging**
