### PR TITLE
english grammar file shortened a bit

### PR DESCRIPTION
**Pull request by sirifarif**
shorter form of grammar file.
remove good morning, evening from Greetings rule

### CODE REVIEW

**Comment by psibre** [comment]
It seems we get random CI failures with some tests in opendial. I've tweaked the test logging so that we get more meaningful exceptions from Travis workers, but it's still a bit volatile. In some cases, it seems that race conditions trigger failed assertions, and simply restarting the test build seems to help.

**Comment by psibre** [comment]
@sirifarif could you please rebase your commit on the current [`upstream/master`](../commit/09d8d1af076641b902fe1d4000423e413c55b016)?

**Comment by psibre** [comment]
replaced by f9a16f9b3cbe02aea0f5e4ce4be0875d4a4901aa

**Comment by LauraRF** [comment]
Hi, 
thanks for shortening the English grammar file, especially the rules concerning the room numbers. 
However, the <RejectEnglish>  and <ConfirmEnglish> rules are gone. Was this done on purpose? In my opinion we really need those.

**Comment by sirifarif** [comment]
Hi LauraRF, 
I think the style rule i.e 
```<style> = hundred | hundred and | <zero>;```
take cares of  the **and** rule. Do u agree?

**Comment by LauraRF** [comment]
Yes, it does, I saw it in the output generated by the expander. But I was talking about the Reject rule (no, that's not what I meant, you're wrong....) and the Confirm rule (yes, that's right, exactly...) which we need if the user wants to agree or disagree if the elevator for example says "I'm now taking you to floor 2" or something like that.

**Comment by HoffmannAJ** [comment]
Hi!

I am a bit confused about how to use the new shorted grammar in the Domain file.
The new one is nice and short but the old version we had made important elements like the floor number easy accessible.
The way it was structured before I simply passed the number or Name to the dm as well as to the nlg.

I could create nlu rules for every floor and every Name. That would be possible. But I think we might not want to do this?

Am I missing something important?
Is there a better way, which allows us a grammar as neat and short as this one and also have a short domain file?

**Pull request closed without merging**
