### PR TITLE
Enable Gradle cache on Travis CI

### PR DESCRIPTION
**Pull request by bryandeng**

### CODE REVIEW

**Comment by bryandeng** [comment]
@psibre

**Comment by psibre** [comment]
Actually, it seems that this does not provide the expected benefit...
[This SO post](http://stackoverflow.com/a/27365925) seems to highlight the problem and possible solutions.
@bryandeng Could you please verify whether caching works for your Travis builds?

**Comment by bryandeng** [comment]
@psibre Yes, several `.lock` files are refreshed during every build.

**Comment by bryandeng** [comment]
@psibre Caching only downloaded dependencies is fairly safe. I'll open a PR for this modification.

**Pull request merged**
