### PR TITLE
Sphinx integration

### PR DESCRIPTION
**Pull request by bryandeng**
This PR resolves https://github.com/EllaVator/EllaVator/issues/24.

For now, acoustic model files are not included (because they are big). They should be under `src/main/resources/acoustic_model`.

Update: We now use acoustic models from `sphinx4` subproject.

### CODE REVIEW

**Comment by bryandeng** [comment]
@sirifarif Test failure caused by https://github.com/EllaVator/EllaVator/commit/3937e162ab3fd82ec75b9a468ab86ec89b4b8c51, not from my changes.

**Comment by sirifarif** [comment]
@bryandeng : Yes, I haven't merge your PR yet.

**Comment by psibre** [comment]
On OSX, the GUI doesn't show -- the app seems to hang...

**Comment by psibre** [comment]
Pushed to [`sphinx-integration` branch](../tree/sphinx-integration)

**Comment by bryandeng** [comment]
@psibre @sirifarif 

It's at least working! 

But by now I have to use CMUdict instead of our own dictionary. When using `ella_en.dict`, recognition won't start and it keeps throwing `java.lang.NullPointerException`.

After consulting [this stackoverflow page](http://stackoverflow.com/questions/27555090/sphinx-4-nullpointerexception-at-startrecognition) and [Sphinx documentation](http://cmusphinx.sourceforge.net/wiki/tutorialam), I think it's because that phonesets of the default acoustic model and our dictionary do not match.

> Phoneset file (your_db.phone) should have one phone per line. The number of phones should match the phones used in the dictionary plus the special SIL phone for silence.

We definitely need our own acoustic model.

**Pull request merged**
