### PR TITLE
Sphinx integration

### PR DESCRIPTION
**Pull request by benti**
In principle the integration works. But the ASR does not work well with OpenDial yet, because Sphinx returns very strange Scores for the recognition result. That's why it is difficult to differentiate noise from speech.

### CODE REVIEW

**Comment by sirifarif** [comment]
How do you actually run the whole thing?

**Comment by psibre** [comment]
@benti I don't think this PR should be merged; there are several issues with a61012f606f7fa7b42587a4d519cd8a14e59b8fa that should be fixed:
* the gradle wrapper files have been deleted, but should not be
* various example dialog files that have nothing to do with our project should not be under `resources`
* cmudict can be declared as an external dependency, instead of being committed into our repo

Perhaps a better approach would be to include [sphinx](/cmusphinx/sphinx4) as a submodule (and update the corresponding dependency in `:opendial`)

**Comment by psibre** [comment]
FWIW, I've pushed a `sphinx` branch to [my fork](/psibre/EllaVator).

**Comment by benti** [comment]
@psibre 
* I don't know why the gradle-wrapper files were lost and I put them back now.
* The dialog files I included are a better testing dialog than the example-simulator.xml we had before, because the dialog answers no matter what the user says. That's why I wanted to use these files until we have our own dialog file. (which already exists on @HoffmannAJ 's computer I think)
* The cmudict I also included for testing only, as we will probably replace it by our own later on.

Anyway, we can also wait merging this, till we have the means to actually make it work properly...

@sirifarif 
The code can be run by "./gradlew run". Then watch the command line for output. By removing one commented line in the SphinxASR plugin, the recognized words can also be fed into the dialog. 

Maybe you have to work around the bug we saw on Wednesday already, which says "resources//settings.xml" cannot be found. I copied "opendial/resources/\*" to "resources/\*", but I think we should find a nicer solution for that.

**Comment by psibre** [comment]
I'll close this, since we have sphinx in a submodule now.

**Pull request closed without merging**
